### ISSUE TITLE
NullException on attribute "Base"

### ISSUE THREAD

**Issue by LouisGameDev** [BenoitFreslon/BitmapFontImporter#3]
I've followed the tutorial and exported as XML-Starling. But on import with the script I get a null exception for the attribute item "base".
[MuseoSans300-export.txt](https://github.com/BenoitFreslon/BitmapFontImporter/files/294571/MuseoSans300-export.txt)

**Comment by BenoitFreslon** [comment]
You can use this Asset store plugin instead:
https://github.com/lite3/Unity-BitmapFontImporter
