### ISSUE TITLE
Getting several catastrophic "read only" errors. Is CharacterInfo permanently deprecated?

### ISSUE THREAD

**Issue by Tylemagne** [BenoitFreslon/BitmapFontImporter#4]
Assets/BitmapFontImporter.cs(53,42): error CS0200: Property or indexer `UnityEngine.CharacterInfo.advance' cannot be assigned to (it is read only)

**Comment by BenoitFreslon** [comment]
Please use this Unity Asset instead:
https://github.com/lite3/Unity-BitmapFontImporter
